from . import start
from . import main_handler
from . import lang_select_handler
from . import main_menu_handler
from . import greet_menu_handler
from . import language_menu_handler
from . import projects_handler
from . import game_guess_handler
from . import weather_handler
from . import parsing_handler
from . import meme_handler
from . import voice_handler
from . import admin_handler